name: Deploy React App on AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
  
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t sanoj8860/reactjs-app:${{ github.sha }} .

      - name: Publish to image docker hub
        run: docker push sanoj8860/reactjs-app:${{ github.sha }}

  deploy:
    needs: build
    runs-on: aws-ec2
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull image from Docker Hub
        run: docker pull sanoj8860/reactjs-app:${{ github.sha }}

      - name: Delete old Container
        run: |
          if [ $(docker ps -a -q --filter name=reactContainer) ]; then  # Check if container exists
            docker rm -f reactContainer  # Remove the container if it exists
          fi
      - name: Run Docker Container
        run: docker run -d -p 3000:80 --name reactContainer sanoj8860/reactjs-app:${{ github.sha }}
